version: '3.7'
services:
 postgres:
  image: postgres:10.7
  restart: always
  volumes:
   - db_data:/var/lib/postgresql/data

 web:
  build: .
  volumes:
   - .:/dockerize_aws_demo
   - gem_cache:/usr/local/bundle/gems
   - node_modules:/app/node_modules
  ports:
   - "3000:3000"
  environment:
    DATABASE_URL: postgres://postgres@postgres:5432
  depends_on:
   - postgres

volumes:
  gem_cache:
  db_data:
  node_modules:
