version: '3'
services:
 postgres:
  image: postgres:10.7
  restart: always
  volumes:
   - ./tmp/db:/var/lib/postgresql/data

 web:
  build: .
  command: bash -c "rm -f tmp/pids/server.pid && bundle exec rails s -p 3000 -b '0.0.0.0'"
  volumes:
   - .:/dockerize_aws_demo
  ports:
   - "3000:3000"
  environment:
    PGHOST: postgres
    PGUSER: postgres
    PGPASSWORD: password
    PGDBNAME: dockerize_aws_demo
    RAILS_MAX_THREADS: 5
  depends_on:
   - postgres
