version: '3.7'
services:
 postgres:
  image: postgres:10.7
  restart: always
  volumes:
   - db_data:/var/lib/postgresql/data

 web:
  build: .
  entrypoint: ./docker-entrypoint.sh
  command: bash -c "rm -f tmp/pids/server.pid && bundle exec rails s -p 3000 -b '0.0.0.0'"
  volumes:
   - .:/dockerize_aws_demo
   - bundle:/bundle
   - node_modules:/app/node_modules
  ports:
   - "3000:3000"
  environment:
    DATABASE_URL: postgres://postgres@postgres:5432
  depends_on:
   - postgres

volumes:
  bundle:
  db_data:
  node_modules:
