default: &default
  adapter: postgresql
  encoding: unicode
  host: postgres
  username: postgres
  password:
  pool: <%= ENV.fetch("RAILS_MAX_THREADS") { 5 } %>

development:
  <<: *default
  database: dockerize_aws_demo_development
test:
  <<: *default
  database: dockerize_aws_demo_test
production:
  <<: *default
  database: dockerize_aws_demo_production
  username: dockerize_aws_demo
  password: <%= ENV['DOCKERIZE_AWS_DEMO_DATABASE_PASSWORD'] %>
