default: &default
  adapter: postgresql
  encoding: unicode
  host: <%= ENV['PGHOST'] %>
  username: <%= ENV['PGUSER'] %>
  password: <%= ENV['PGPASSWORD'] %>
  pool: <%= ENV.fetch("RAILS_MAX_THREADS") { 5 } %>

development:
  <<: *default
  database: <%= ENV['PGDBNAME'] %>_development
test:
  <<: *default
  database: <%= ENV['PGDBNAME'] %>_test
production:
  <<: *default
  database: <%= ENV['PGDBNAME'] %>_production
