default: &default
  adapter: postgresql
  encoding: unicode
  url: <%= ENV.fetch("DATABASE_URL") { "postgres://postgres@localhost" } %>
  pool: <%= ENV.fetch("RAILS_MAX_THREADS") { 5 } %>

development:
  <<: *default
  database: dockerize_aws_demo_development
test:
  <<: *default
  database: dockerize_aws_demo_test
production:
  <<: *default
  database: dockerize_aws_demo_production
